server.port=8090
spring.application.name=api-gateway-bff
spring.main.web-application-type=reactive

# --- RUTAS DE LOS MICROSERVICIOS ---
spring.cloud.gateway.routes[0].id=patient-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/patients/**

spring.cloud.gateway.routes[1].id=request-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/requests/**

#ruta hacia la waiting-list 
## --- RUTA LISTA DE ESPERA (8083) ---
spring.cloud.gateway.routes[2].id=waiting-list-docs
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/waiting-list/v3/api-docs
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/api/waiting-list/v3/api-docs, /v3/api-docs

spring.cloud.gateway.routes[3].id=waiting-list-service
spring.cloud.gateway.routes[3].uri=http://localhost:8083
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/waiting-list/**
# --- CONFIGURACIÓN DE SWAGGER ---
# Esto redirige las llamadas de Swagger a través del Gateway
springdoc.swagger-ui.urls[0].name=Pacientes (8081)
springdoc.swagger-ui.urls[0].url=/api/patients/v3/api-docs
springdoc.swagger-ui.urls[1].name=Solicitudes (8082)
springdoc.swagger-ui.urls[1].url=/api/requests/v3/api-docs

## --- CONFIGURACIÓN DE SWAGGER EN EL GATEWAY ---
springdoc.swagger-ui.urls[2].name=Lista de Espera (8083)
springdoc.swagger-ui.urls[2].url=/api/waiting-list/v3/api-docs

# IMPORTANTE: Si te sigue dando 404, prueba quitando o poniendo esta línea:
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.server-strategy=relative

# Conservar el Host original (localhost:8090) al redirigir las peticiones
spring.cloud.gateway.x-forwarded.host-enabled=true
spring.cloud.gateway.x-forwarded.port-enabled=true


spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*