server.port=8090
spring.application.name=api-gateway-bff
spring.main.web-application-type=reactive

# ===================================================================
# --- CONFIGURACIÓN DE EUREKA CLIENT ---
# ===================================================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# ===================================================================
# --- CONFIGURACIÓN DE SWAGGER (DOCUMENTACIÓN) ---
# ===================================================================
springdoc.swagger-ui.urls[0].name=Pacientes (8081)
springdoc.swagger-ui.urls[0].url=/api/patients/v3/api-docs
springdoc.swagger-ui.urls[1].name=Solicitudes (8082)
springdoc.swagger-ui.urls[1].url=/api/requests/v3/api-docs
springdoc.swagger-ui.urls[2].name=Lista de Espera (8083)
springdoc.swagger-ui.urls[2].url=/api/waiting-list/v3/api-docs

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.server-strategy=relative

# Conservar el Host original en WebFlux
spring.cloud.gateway.server.webflux.x-forwarded.host-enabled=true
spring.cloud.gateway.server.webflux.x-forwarded.port-enabled=true

# ===================================================================
# --- CONFIGURACIÓN DE CORS DEFENSA PERIMETRAL (VERSIÓN WEBFLUX ACTUALIZADA) ---
# ===================================================================
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true

# Filtro reactivo definitivo para evitar la duplicación de cabeceras en el navegador
spring.cloud.gateway.server.webflux.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST