server.port=8090
spring.application.name=api-gateway-bff
spring.main.web-application-type=reactive

# --- RUTAS DE LOS MICROSERVICIOS ---
spring.cloud.gateway.routes[0].id=patient-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/patients/**

spring.cloud.gateway.routes[1].id=request-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/requests/**

# --- CONFIGURACIÓN DE SWAGGER ---
# Esto redirige las llamadas de Swagger a través del Gateway
springdoc.swagger-ui.urls[0].name=Pacientes (8081)
springdoc.swagger-ui.urls[0].url=/api/patients/v3/api-docs
springdoc.swagger-ui.urls[1].name=Solicitudes (8082)
springdoc.swagger-ui.urls[1].url=/api/requests/v3/api-docs

# IMPORTANTE: Si te sigue dando 404, prueba quitando o poniendo esta línea:
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.server-strategy=relative