server.port=8083
spring.application.name=waiting-list-service

# Base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:waitinglistdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Forzar a Swagger a mostrar la URL del Gateway al hacer Execute
server.forward-headers-strategy=framework

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

#para que Spring ejecute SQL al iniciar para el usuario precargado de SQL
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.web.mvc.cors.enabled=false