server.port=8083
spring.application.name=waiting-list-service

# Base de datos USANDO H2 DE PRUEBA 
spring.datasource.url=jdbc:h2:mem:waitinglistdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# CRÍTICO: Forzar a Swagger a mostrar la URL del Gateway (8090) al hacer Execute
server.forward-headers-strategy=framework

