# Configuración del Servidor
server.port=8081
spring.application.name=patient-service

# Configuración de Base de Datos H2
spring.datasource.url=jdbc:h2:mem:patientdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Mostrar el SQL en consola
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Actualización automática de la tabla
spring.jpa.hibernate.ddl-auto=update

# Springdoc - ruta por defecto para que el Gateway pueda hacer rewrite
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Headers del Gateway
server.forward-headers-strategy=framework

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true


#para que Spring ejecute SQL al iniciar para el usuario precargado de SQL
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.mvc.cors.enabled=false
springdoc.api-docs.enabled=true
spring.web.mvc.cors.enabled=false


springdoc.swagger-ui.disable-swagger-default-url=true
spring.mvc.cors.enabled=false